---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/stefanprodan/charts/podinfo
