---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-fundamentals
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/tiesmaster/gitops-fundamentals-exercises.git
