---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./exercises/kustomize-controller/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-fundamentals
