---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo2
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: fundamentals-training
  chart:
    spec:
      chart: podinfo
      version: ">=6.0.2 <7.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    # Default values for podinfo.
    replicaCount: 1
    logLevel: info
    ui:
      color: "#34577c"
      message: "This Helm Release is done with Flux"
      logo: ""

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: tiesmaster.dev.iks.guida.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-tls
          hosts:
            - tiesmaster.dev.iks.guida.io
